#!/bin/bash

# Name:        bgman
# Author:      Petar Katić (bratpeki)
# Description: Manage background images using feh
#              This script is intended to be used on WM's, since most, if
#              not all, modern DE's have their own background image tools.
#              This one was made specifically for dwm.
#              $HOME/.fehbg is created after using bgman and loads as part of
#              my dwm's startup script

# Edit this location with the place you want to recursively search for the images in
pictureLocation="$HOME/Pictures/"

pictureLocation="$(find $pictureLocation -type f ! -wholename "*/.*" | dmenu -p "Picture: " -i -l 25)"
pictureMode="$(printf "center\nfill\nmax\nscale\ntile" | dmenu -p "Mode: " -i -l 25)"

if [ -z "$pictureLocation" ] || [ -z "$pictureMode" ]; then
	exit
fi

feh --bg-$pictureMode "$pictureLocation"
