#!/bin/bash

# Name:        bgman
# Author:      Petar Katić (bratpeki)
# Type:        dmenu
# Description: Manage background images using feh
#              This script is intended to be used on WM's, since most, if
#              not all, modern DE's have their own background image tools.
#              This one was made specifically for dwm.
#              You should make sure "bgman -l" is run on startup to ensure
#              that your image is applied
# Arguments:
#              -l (Load - Load your saved configuration)

locationOfCfg="$HOME/.config/bash-scripts/bgman"

if [ "$1" == "-l" ] || [ "$1" == "-L" ]; then
	feh --bg-$(sed '1q;d' "$locationOfCfg") "$(sed '2q;d' "$locationOfCfg")"
else

	# Edit this location with the place you want to recursively search for the images in
	pictureLocation="$HOME/Pictures/"

	pictureLocation="$(find $pictureLocation -type f | dmenu -p "Picture: " -i -l 25)"
	pictureMode="$(printf "center\nfill\nmax\nscale\ntile" | dmenu -p "Mode: " -i -l 25)"

	if [ -z "$pictureLocation" ] || [ -z "$pictureMode" ]; then
		exit
	fi

	feh --bg-$pictureMode "$pictureLocation"

	if test -f "$locationOfCfg"; then
		rm "$locationOfCfg"
	fi

	touch "$locationOfCfg"
	printf "$pictureMode\n$pictureLocation" > "$locationOfCfg"

fi
