#!/bin/bash

# Name:        brightness
# Author:      Petar Katić (bratpeki)
# Description: Control the screen brightness via ``xrandr``
#              The "display" variable will contain the display whose brightness
#              will be edited, if you have multiple desktops you could set up a
#              dmenu prompt to choose the screen you affect
# Arguments:   None or floating point value between 0 and 1
# Example:
#
#     $ brightness
#     Insert desired brightness [0-1]: 0.8
#
#     $ brightness 0.8

display="eDP1"

if [ -z "$1" ]; then
	printf "Insert desired brightness [0-1]: "
	read a
else
	a="$1"
fi

if [ "$(echo "$(echo "$a"'>'"0.05" | bc -l) $(echo "$a"'<='"1" | bc -l)")" == "1 1" ]; then
	xrandr --output "$display" --brightness "$a"
fi

