#!/bin/bash

# Name:        brightness
# Author:      Petar Katić (bratpeki)
# Type:        terminal
# Description: Control the screen brightness via ``xrandr``
#              The "display" variable will contain the display whose brightness
#              will be edited, if you have multiple desktops you could set up a
#              dmenu prompt to choose the screen you affect
#              By default, the user is limited between 0.05 and 1
# Arguments:   -a (All - Alows for any number input)
# Example:
#
#     $ brightness
#     Insert desired brightness [0-1]: 0.8
#


# Insert the name of your display here
# To do that, find which screen is connected using "xrandr -q"
display="eDP1"

if [ "$1" == "-a" ]; then
	printf "Insert desired brightness: "
	read a
else
	printf "Insert desired brightness [0-1]: "
	read a

	if [ "$(echo "$a"'<'"0.05" | bc -l)" == "1" ] || [ "$(echo "$a"'>'"1" | bc -l)" == "1" ]; then
		exit
	fi

fi

xrandr --output "$display" --brightness "$a"
