#!/bin/bash

# Name:        brightness
# Author:      Petar Katić (bratpeki)
# Description: Control the screen brightness via ``xrandr``
# Arguments:   None or floating point value between 0 and 1

display="eDP1"

if [ -z "$1" ]; then
	printf "Insert desired brightness [0-1]: "
	read a
else
	a="$1"
fi

if [ "$(echo "$(echo "$a"'>'"0" | bc -l) $(echo "$a"'<='"1" | bc -l)")" == "1 1" ]; then
	xrandr --output "$display" --brightness "$a"
fi

