#!/bin/bash

# Name:        connman
# Author:      Petar Katić (bratpeki)
# Type:        terminal in (spawn), dmenu
# Description: bluetooth and nmcli-based wireless connection manager
# Example:     None provided, script uses graphical tool(s)

btState="$(bluetooth | awk '{ print $3 }')"

# For the sake of universality, I'll have everything use "enabled" and "disabled" rather
# than something using "on" and "off"
case "$btState" in
	"on") btState="enabled";;
	"off") btState="disabled";;
esac

opt="$(printf "BlueTooth - Enable/Disable ("$btState")\nWiFi - Enable/Disable ("$(nmcli radio wifi)")\nWiFi - Connect" | dmenu -p "Options:" -i -l 25)"

case "$opt" in
	"Bluetooth - Enable/Disable ($btState)")
		bluetooth toggle
		;;
	"WiFi - Enable/Disable (enabled)")
		nmcli radio wifi off
		notify-send "connman" "WiFi Disabled"
		;;
	"WiFi - Enable/Disable (disabled)")
		nmcli radio wifi on
		notify-send "connman" "WiFi Enabled"
		;;
	"WiFi - Connect")
		echo "Getting networks..."
		nmcliAll="$(nmcli dev wifi)"
		nmcliLines="$(echo "$nmcliAll" | wc -l)"

		networkRaw="$(echo "$nmcliAll" | tail -n $(($nmcliLines - 1)) | dmenu -p "Network:" -i -l 25)"

		if [ -z "$networkRaw" ]; then
			echo "No selection, exiting..."
			exit
		fi

		if [ "$(echo "$networkRaw" | head -c 1)" == "*" ]; then
			ssid="$(echo "$networkRaw" | awk -F "  " '{ print $5 }')"
		else
			ssid="$(echo "$networkRaw" | awk -F "  " '{ print $6 }')"
		fi

		st -e nmcli dev wifi connect "$ssid" --ask
		;;
esac
