#!/bin/bash

# Name:        goto
# Author:      Petar Katić (bratpeki)
# Type:        terminal out, dmenu
# Description: Quickly access direcoties
#              The user has to define an EXPLORER variable (vifm, ranger, nnn, vim, dolphin ...)
#              Otherwise, "$EXPLORER" should just be replaced with some explorer of choice
#              Here, I'm taking "st" into account; therefore, when the arg "-l" is not specified
#              I'm running "st -e $EXPLORER "directory"", since that is how a new "st" instance starts
#              with a given command
# Arguments:
#              -l ( Local execution - Execute command from current shell )
# Example:     None provided, script uses graphical tool(s)

# "-type d" is not necessary if the explorer of choice doubles as an editor
# excluding paths can preferrably be done by using "!/-not -path "*word-in-your-path*""
findCommand="find $HOME -maxdepth 5 -type d"

echo "Getting directories..."
directory="$($findCommand | dmenu -i -l 25)"

if [ -z "$directory" ]; then
	echo "No selection, exiting..."
else
	if [ "$1" == "-l" ] || [ "$1" == "-L" ]; then
		$EXPLORER "$directory"
	else
		# Replace this with your browser of choice
		# In Konsole: konsole -e bash -c $EXPLORER "$directory"
		# In GNOME Terminal: gnome-terminal -- bash -c "$EXPLORER "$directory"; exec bash"
		st -e $EXPLORER "$directory"
	fi
fi
