#!/bin/bash

# Name:        kblayout
# Author:      Petar Katić (bratpeki)
# Type:        terminal args (local), dmenu
# Description: Manage keyboard layouts in X
#              deps/kblayout is to be edited manually
# Arguments:
#              -f ( Favorites - List favorites from a file)
# Example:     None provided, script uses graphical tool(s)

locationOfCfg="$HOME/.config/bash-scripts/kblayout"

if test -f "$locationOfCfg"; then
	if [ "$1" == "-f" ] || [ "$1" == "-F" ]; then
		sel="$(dmenu -i -l 25 < "$locationOfCfg")"
	else
		sel="$(localectl list-x11-keymap-layouts | dmenu -i -l 25)"
	fi
	if [ -n "$sel" ]; then setxkbmap "$sel"; fi
else
	printf "de\ngb\nrs" > "$locationOfCfg"
	kblayout
fi
