#!/bin/bash

# Name:        lmmsProjectBooter
# Author:      Petar Katić (bratpeki)
# Description: Load projects from a specific directory into LMMS
# Arguments:
#              -d ( Debug mode - Get LMMS debug output )
# Example:     None provided, script uses graphical tool(s)

currDir="$(pwd)"
cd "$HOME"/Music/Prod/lmms/projects || exit

fileInQuestion="$(find . \( -name "*.mmpz" -or -name "*.mmp" \) -type f -exec realpath {} \; | dmenu -i -l 25)"

if [ -z "$fileInQuestion" ]; then
	notify-send "lmmsProjectBooter" "No selection, exiting..."
else
	echo Opening \""$fileInQuestion"...\"
	if [ "$1" == "-d" ] || [ "$1" == "-D" ]; then
		lmms "$fileInQuestion" &
	else
		lmms "$fileInQuestion" &> /dev/null &
	fi
fi

cd "$currDir" || exit
