#!/bin/bash

# Name:        lmmsProjectBooter
# Author:      Petar Katić (bratpeki)
# Type:        terminal args, dmenu
# Description: Load projects from a specific directory into LMMS
# Arguments:
#              -d ( Debug mode - Get LMMS debug output )
# Example:     None provided, script uses graphical tool(s)

currDir="$(pwd)"
cd "$HOME"/Documents/lmms/projects || exit

fileInQuestion=$(find . -name "*.mmpz" | dmenu -i -l 25 -fn "monospace:bold:pixelsize=16")

if [ -z "$fileInQuestion" ]; then
	notify-send "lmmsProjectBooter" "No selection, exiting..." -t 3000
else
	echo Opening \""$fileInQuestion"...\"
	if [ "$1" == "-d" ] || [ "$1" == "-D" ]; then
		lmms "$fileInQuestion" &
	else
		lmms "$fileInQuestion" &> /dev/null &
	fi
fi

cd "$currDir" || exit
