#!/bin/bash

# Return specific nerd font characters into stdout

locationOfFile=$(which nerdFontItemPicker)
locationOfFile=${locationOfFile%nerdFontItemPicker}deps/nerdFontItemPicker

cat $locationOfFile | dmenu -l 25 -fn "Monospace:bold:pixelsize=16" | awk '{print $2}'
