#!/bin/bash

# Name:        wifiman
# Author:      Petar Katić (bratpeki)
# Description: nmcli-based wireless connection manager

notify-send "wifiman" "Getting networks..." -t 3000
nmcliAll="$(nmcli dev wifi)"
nmcliLines="$(echo "$nmcliAll" | wc -l)"

networkRaw="$(echo "$nmcliAll" | tail -n $(($nmcliLines - 1)) | dmenu -p "Network:" -l 25)"

if [ -z "$networkRaw" ]; then
	notify-send "wifiman" "No selection, exiting..." -t 3000
	exit
fi

if [ "$(echo "$networkRaw" | head -c 1)" == "*" ]; then
	ssid="$(echo "$networkRaw" | awk -F "  " '{ print $5 }')"
else
	ssid="$(echo "$networkRaw" | awk -F "  " '{ print $6 }')"
fi

nmcli dev wifi connect "$ssid" --ask

