#!/bin/bash

# Name:        wifiman
# Author:      Petar Katić (bratpeki)
# Type:        terminal in, dmenu
# Description: nmcli-based wireless connection manager

opt="$(printf "Enable/Disable WiFi ("$(nmcli radio wifi)")\nConnect" | dmenu -p "Options:" -l 25)"

case "$opt" in
	"Enable/Disable WiFi (enabled)")
		nmcli radio wifi off
		notify-send "wifiman" "WiFi Disabled"
		;;
	"Enable/Disable WiFi (disabled)")
		nmcli radio wifi on
		notify-send "wifiman" "WiFi Enabled"
		;;
	"Connect")
		echo "Getting networks..."
		nmcliAll="$(nmcli dev wifi)"
		nmcliLines="$(echo "$nmcliAll" | wc -l)"

		networkRaw="$(echo "$nmcliAll" | tail -n $(($nmcliLines - 1)) | dmenu -p "Network:" -l 25)"

		if [ -z "$networkRaw" ]; then
			echo "No selection, exiting..."
			exit
		fi

		if [ "$(echo "$networkRaw" | head -c 1)" == "*" ]; then
			ssid="$(echo "$networkRaw" | awk -F "  " '{ print $5 }')"
		else
			ssid="$(echo "$networkRaw" | awk -F "  " '{ print $6 }')"
		fi

		nmcli dev wifi connect "$ssid" --ask
		;;
esac
