#!/bin/bash

# Name:        wttrin
# Author:      Petar Katić (bratpeki)
# Description: Read wetter information via curl using a custom location argument
# Arguments:   None or infinitely many

if [ $# -eq 0 ]; then
	echo No arguments, getting weather for your location
	curl wttr.in/
	exit
fi

while [ $# -gt 0 ]; do
	echo Looking up weather for \""$1"\"
	curl wttr.in/~"$1"
	shift
done
